//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_WSBEntities : DbContext
    {
        public DB_WSBEntities()
            : base("name=DB_WSBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActaConfirmacionCita> tActaConfirmacionCita { get; set; }
        public virtual DbSet<tCalendario> tCalendario { get; set; }
        public virtual DbSet<tCometario> tCometario { get; set; }
        public virtual DbSet<tDia> tDia { get; set; }
        public virtual DbSet<tEstado> tEstado { get; set; }
        public virtual DbSet<tMenu> tMenu { get; set; }
        public virtual DbSet<tMunicipio> tMunicipio { get; set; }
        public virtual DbSet<tRol> tRol { get; set; }
        public virtual DbSet<tUsuario> tUsuario { get; set; }
    }
}
