//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActaConfirmacionCita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tActaConfirmacionCita()
        {
            this.tCometario = new HashSet<tCometario>();
        }
    
        public int idActa { get; set; }
        public Nullable<int> idUsuarioP { get; set; }
        public Nullable<int> idUsuarioC { get; set; }
        public Nullable<int> idCalendario { get; set; }
        public Nullable<int> bEstatus { get; set; }
        public string sMotivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCometario> tCometario { get; set; }
        public virtual tCalendario tCalendario { get; set; }
        public virtual tUsuario tUsuario { get; set; }
        public virtual tUsuario tUsuario1 { get; set; }
    }
}
