//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCalendario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCalendario()
        {
            this.tActaConfirmacionCita = new HashSet<tActaConfirmacionCita>();
        }
    
        public int idCalendario { get; set; }
        public Nullable<int> idUsuarioP { get; set; }
        public Nullable<int> idDia { get; set; }
        public string sHorarioInicio { get; set; }
        public string sHorarioFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActaConfirmacionCita> tActaConfirmacionCita { get; set; }
        public virtual tDia tDia { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
