//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCometario
    {
        public int idComentario { get; set; }
        public Nullable<int> idAcata { get; set; }
        public string sComentario { get; set; }
        public Nullable<int> iCalificacion { get; set; }
    
        public virtual tActaConfirmacionCita tActaConfirmacionCita { get; set; }
    }
}
