//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenu
    {
        public int idMenu { get; set; }
        public Nullable<int> idRol { get; set; }
        public string sRuta { get; set; }
        public string sDescripcion { get; set; }
        public Nullable<int> idRutaPadre { get; set; }
    
        public virtual tRol tRol { get; set; }
    }
}
