//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSecureBookings.App_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUsuario()
        {
            this.tActaConfirmacionCita = new HashSet<tActaConfirmacionCita>();
            this.tActaConfirmacionCita1 = new HashSet<tActaConfirmacionCita>();
            this.tCalendario = new HashSet<tCalendario>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
        public System.DateTime dFechaRegistro { get; set; }
        public string sNombre { get; set; }
        public string sApellidoP { get; set; }
        public string sApellidoM { get; set; }
        public string sCorreo { get; set; }
        public string stelefono { get; set; }
        public string sProfecion { get; set; }
        public string sAreaProfesion { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public string sColonia { get; set; }
        public string sCalle { get; set; }
        public string sUbicacion { get; set; }
        public Nullable<bool> bEstatus { get; set; }
        public string sToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActaConfirmacionCita> tActaConfirmacionCita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActaConfirmacionCita> tActaConfirmacionCita1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCalendario> tCalendario { get; set; }
        public virtual tMunicipio tMunicipio { get; set; }
        public virtual tRol tRol { get; set; }
    }
}
